mock_weather_response = {
    "country_code": "US",
    "lon": -84.19161,
    "timezone": "America New_York",
    "lat": 39.75895,
    "alerts": [
        {
            "regions": [
                "Madison",
                " Franklin",
                " Scioto",
                " Hardin",
                " Logan",
                " Licking",
                " Montgomery",
                " Clermont",
                " Fayette",
                " Brown",
                " Mercer",
                " Wayne",
                " Adams",
                " Union",
                " Warren",
                " Highland",
                " Lewis",
                " Ross",
                " Robertson",
                " Clark",
                " Fayette",
                " Preble",
                " Shelby",
                " Clinton",
                " Franklin",
                " Pike",
                " Miami",
                " Delaware",
                " Bracken",
                " Greene",
                " Auglaize",
                " Hocking",
                " Fairfield",
                " Butler",
                " Champaign",
                " Pickaway",
                " Darke",
                " Mason",
                " Union"
            ],
            "ends_utc": "2020-10-17T13:00:00",
            "effective_local": "2020-10-16T14:17:00",
            "onset_utc": "2020-10-17T06:00:00",
            "expires_local": "2020-10-16T22:30:00",
            "expires_utc": "2020-10-17T02:30:00",
            "ends_local": "2020-10-17T09:00:00",
            "uri": "https:\/\/api.weather.gov\/alerts\/NWS-IDP-PROD-4486346-3727122",
            "onset_local": "2020-10-17T02:00:00",
            "effective_utc": "2020-10-16T18:17:00",
            "severity": "Watch",
            "title": "Freeze Warning issued October 16 at 2:17PM EDT until October 17 at 9:00AM EDT by NWS Wilmington OH",
            "description": "* WHAT...Sub-freezing temperatures as low as 30 expected.\n\n* WHERE...Portions of East Central and Southeast Indiana,\nNortheast and Northern Kentucky and Central, South Central,\nSouthwest and West Central Ohio.\n\n* WHEN...From 2 AM to 9 AM EDT Saturday.\n\n* IMPACTS...Frost and freeze conditions will kill crops, other\nsensitive vegetation and possibly damage unprotected outdoor\nplumbing."
        }
    ],
    "city_name": "Dayton",
    "state_code": "OH"
}
